### ISSUE TITLE
Problems with missing notmuch

### ISSUE THREAD

**Issue by leophys** [boyska/mailbundle#6]
My installation of this super cool mail client shows some problems. Afew needs notmuch python(3) bindings, but I cannot find them in `dep/ve3/lib/python3.6/site-packages`.
This led to an error in executing afew

```
ok stderr:Traceback (most recent call last):
  File "/opt/mailbundle/dep/ve3/bin/afew", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/mailbundle/dep/ve3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/opt/mailbundle/dep/ve3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/opt/mailbundle/dep/ve3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/mailbundle/dep/ve3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/opt/mailbundle/dep/ve3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/mailbundle/dep/ve3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'notmuch' distribution was not found and is required by afew

```

I solved manually linking the (systemwide) installed bindings

```
% ln -s /usr/lib/python3.6/site-packages/notmuch
% ln -s /usr/lib/python3.6/site-packages/notmuch-0.24.1-py3.6.egg-info
```

Is there anything wrong with what I did?

**Comment by boyska** [comment]
Blallo:
>My installation of this super cool mail client shows some problems. Afew needs notmuch python(3) bindings, but I cannot find them in `dep/ve3/lib/python3.6/site-packages`.

>I solved manually linking the (systemwide) installed bindings

>Is there anything wrong with what I did?

I think you should have done ./dep/ve3/bin/pip install afew

but if that works for you, that's fine
